### ISSUE TITLE
TODO before the first release

### ISSUE THREAD

**Issue by nana-4** [nana-4/mica-plasma-theme#1]
- [x] Fix broken button background (#2)
- [x] Fix broken tooltip shadow ([upstream fix](https://invent.kde.org/frameworks/plasma-framework/-/commit/6e660cfd0c6aef60c9765f76d8d2b6fcbd91176d))
- [x] Update background opacities
- [ ] Update `network.svg`
